# Site
repository: p15xiar/cv-1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Spyros Xiarchos
title: Undergraduate Informatics Student
email: sp@xiarchos.gr
website: https://xiarchos.gr

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: p15xiar

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there, I’m Spyros and I am senior student in the Department of Informatics of the Ionian University. 
  During my studies I gained a wide experience in the following fields:
  - Constructive wireless networks 
  - Hardware maintenance and repairing
  - E-shop creation 
  - Website creation 
  Apart from the technical skills that I built through my experience in several companies, I consider myself as a great team player and strong analytical thinker.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc. Informatics
        caption: 10/2015 - Present
        sub_title: Ionian University, GR
        description: | # this will include new lines to allow paragraphs
          Specialisation in Information Systems.
          Main subjects of the currculum follow:
          • Strategy and Management of Information Systems
          • Analysis and Deisgin of Information Systems
          • Supply Chain and Information Systems
          • Electronic Commerce

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Messinian Networks | MNET | Kalamata
        sub_title: Network Construction Assistant
        caption:  09/2016 - 08/2018
        quote: >
          Wireless Network Construction | Internet Provider 
        description: | # this will include new lines to allow paragraphs
          As Network Constructor for MNET I've worked on establishing wireless links up to 15km. 
    content:
      - layout: left
        title: Spyretos Computer Service & Repair | Corfu
        sub_title: Computer Repair Assistant
        caption: 08/2018 - 08/2019
        quote: >
          Computer Service and Repair 
        description: | # this will include new lines to allow paragraphs
          As assistant in Spyretos' lab I've worked on a lot of computer repairs and .
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Apart from the job related interests I'm keen on:
      - Vinyl Record Collection
      - Cooking
      - Hiking
      - MotoGP Fan
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

