# Site
repository: p15xiar/cv-1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Spiros Xiarchos
title: Information Systems Specialist
email: sp@xiarchos.gr
website: xiarchos.gr

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: p15xiar
linkedin_username: spxiar

additional_links:
- title: CV in PDF format
  icon: fas fa-file
  url: https://xiarchos.gr/pdf/cv.pdf

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there, Iâ€™m Spyros and I am a senior student in the Department of Informatics of the Ionian University. 
  During my studies I gained a wide experience in the following fields:
  - Constructive wireless networks 
  - Hardware maintenance and repairing
  - E-shop creation 
  - Website creation 
  
  On top of the technical skills that were built throughout my experience in several companies, I consider myself as a great team player and strong analytical thinker.

content:        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc. Informatics
        caption: 10/2015 - Present
        sub_title: Ionian University, GR
        description: | # this will include new lines to allow paragraphs
          Specialization in Information Systems.
          
          Main courses follow:
          - Strategy & Management of Information Systems
          - Analysis & Design of Information Systems
          - Information Systems & Supply Chain
          - Electronic Commerce
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Web and Sound Services Freelancer
        sub_title: Freelance
        caption: 09/2019 - Present
        description: | # this will include new lines to allow paragraphs
          - Web Site Creation and Development
          - E-Shop Creation and Development
          - Sound Design and Mix
      - layout: left
        title: Hardware Maintainance and Repairing Assistant
        sub_title: Spyretos Computer Service and Repair, Corfu GR
        caption: 08/2018 - 08/2019
        description: | # this will include new lines to allow paragraphs
          - Hardware Repairing & Maintenance
          - IT Technical Support
          - Customer Care Services
      - layout: left
        title: Network Expansion Assistant
        sub_title: MNET, Kalamata GR
        caption:  11/2015 - 08/2018
        description: | # this will include new lines to allow paragraphs
          - Wireless Link Expansion and Maintenance
          - IT Tech Support
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Apart from the job related interests I'm keen on:
      - Tech Savvy
      - Vinyl Record Collection
      - Music Production
      - Hiking
      - MotoGP Fan
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

