# Site
repository: p15xiar/cv-1

# Content configuration version
version: 2

# Personal info
name: Spyros Xiarchos
title: Undergraduate Informatics Student
email: sp@xiarchos.gr
website: https://xiarchos.gr

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  p15xiar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: pipisxi
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Spyros and I'm a senior network constructor and undergraduate student of Ionian University at the Department of Informatics. As well as constructing wireless networks I also have experience making websites and e-shops. I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>ubiquiti</mark> and <mark>Mikrotik</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Messinian Networks | MNET | Kalamata
        sub_title: Senior Network Constructor
        caption: September 2016 - August 2020
        quote: >
          Wireless Network Construction | Internet Provider 
        description: | # this will include new lines to allow paragraphs
          As Network Constructor for MNET I've worked on establishing wireless links up to 15km. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University | Department of Informatics | Corfu
        caption: 2015 - 2022
        sub_title: BSc Information Systems
        quote: >
          The Ionian University was founded in 1984, the same year as the University of Thessaly and the University of the Aegean. The university comprises five faculties and twelve departments. Its seat is in Corfu, with university units in Lefkada, Kefalonia and Zakynthos.
        description: | # this will include new lines to allow paragraphs
          During my stay at Corfu I wanted to practice everything i got learned in class. That's why from the start of my second year in the university I started searching for work.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks some of my other interests and hobbies are:
      - Vinyl Record Collection
      - Cooking
      - Hiking
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
